const fs = require('fs')
const path = require('path')
const tjs = require('typescript-json-schema')

const program = tjs.getProgramFromFiles([
	path.resolve('src/cli/cli.ts')
])

const schema = tjs.generateSchema(program, 'ConfigOptions', {
	noExtraProps: true,
	required: true,
	strictNullChecks: true,
	ignoreErrors: true,
	excludePrivate: true
})

const tableItems = Object.entries(schema.properties).sort(([a], [b]) => a > b ? 1 : a < b ? -1 : 0).map(([key, property]) =>
	`| \`${key}\` | \`${property.type}\` | ${property.description} | \`${property.default}\` |`
)

let markdown = ''
markdown += '<!-- This file is auto-generated by the config-docs workflow. -->'
markdown += '\n\n# Config'
markdown += `\n\n| name | type | description | default |\n| :- | :- | :- | :- |\n${tableItems.join('\n')}\n`

fs.writeFileSync('docs/guides/config.md', markdown)