import './polyfill'
export { parse } from './parser'
export { Program } from '../program'
export { Diagnostic, Severity } from '../diagnostic'
export { Binding, BindingData, BindingExpression, BindingName, DiagNode, Document, Node, NodeType, ViewModelNode } from './bindingDOM'
export { createDocument } from './document-builder'